# .slather.yml

xcodeproj: AUParamsApp/AUParamsApp.xcodeproj
workspace: AUParamsApp.xcworkspace
scheme: AUParamsApp
output_directory: ./testcoverage-reports

# source_directory: Pod/Classes
# binary_basename: AUParamsApp
# input_format: profdata
# coverage_service: coveralls
# ci_service: travis_pro
# ci_access_token: coveralltoken

ignore:
- Pods/*
